# Generated by Django 4.1.3 on 2022-11-08 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Emp_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='sal_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Emp_App.person_details'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salary',
            name='emp_id',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
