# Generated by Django 4.1.1 on 2022-12-03 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Emp_App', '0002_salary_sal_id_alter_salary_emp_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='emp_id',
            field=models.IntegerField(max_length=15, null=True),
        ),
    ]
